apiVersion: v1
kind: Service
metadata:
  name: { { include "database.fullname" . } }
  labels: { { - include "database.labels" . | nindent 4 } }
spec:
  selector:
    app: { { include "database.fullname" . } }
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
