// Code generated by go generate; DO NOT EDIT.
package columns

var BannersTableName = "banners"

// BannerColumns provides type-safe access to Banner database columns
type BannerColumns struct{}

func (c BannerColumns) TableName() string { return BannersTableName }

func (c BannerColumns) ID() string { return "id" }
func (c BannerColumns) NameVi() string { return "name_vi" }
func (c BannerColumns) NameEn() string { return "name_en" }
func (c BannerColumns) NameZh() string { return "name_zh" }
func (c BannerColumns) DescriptionVi() string { return "description_vi" }
func (c BannerColumns) DescriptionEn() string { return "description_en" }
func (c BannerColumns) DescriptionZh() string { return "description_zh" }
func (c BannerColumns) Position() string { return "position" }
func (c BannerColumns) Status() string { return "status" }
func (c BannerColumns) ResourceID() string { return "resource_id" }
func (c BannerColumns) Link() string { return "link" }
func (c BannerColumns) ButtonNameVi() string { return "button_name_vi" }
func (c BannerColumns) ButtonNameEn() string { return "button_name_en" }
func (c BannerColumns) ButtonNameZh() string { return "button_name_zh" }
func (c BannerColumns) HasContent() string { return "has_content" }

