// Code generated by go generate; DO NOT EDIT.
package domain

// BannerColumns provides type-safe access to Banner database columns
type BannerColumns struct{
	name string
}

func (c BannerColumns) Column() string { return c.name }

func (c BannerColumns) ID() BannerColumns { return BannerColumns{name: "id"} }
func (c BannerColumns) NameVi() BannerColumns { return BannerColumns{name: "name_vi"} }
func (c BannerColumns) NameEn() BannerColumns { return BannerColumns{name: "name_en"} }
func (c BannerColumns) NameZh() BannerColumns { return BannerColumns{name: "name_zh"} }
func (c BannerColumns) DescriptionVi() BannerColumns { return BannerColumns{name: "description_vi"} }
func (c BannerColumns) DescriptionEn() BannerColumns { return BannerColumns{name: "description_en"} }
func (c BannerColumns) DescriptionZh() BannerColumns { return BannerColumns{name: "description_zh"} }
func (c BannerColumns) Position() BannerColumns { return BannerColumns{name: "position"} }
func (c BannerColumns) Status() BannerColumns { return BannerColumns{name: "status"} }
func (c BannerColumns) ResourceID() BannerColumns { return BannerColumns{name: "resource_id"} }
func (c BannerColumns) Link() BannerColumns { return BannerColumns{name: "link"} }
func (c BannerColumns) ButtonNameVi() BannerColumns { return BannerColumns{name: "button_name_vi"} }
func (c BannerColumns) ButtonNameEn() BannerColumns { return BannerColumns{name: "button_name_en"} }
func (c BannerColumns) ButtonNameZh() BannerColumns { return BannerColumns{name: "button_name_zh"} }
func (c BannerColumns) HasContent() BannerColumns { return BannerColumns{name: "has_content"} }

