// Code generated by go generate; DO NOT EDIT.
package domain

// BannerFields provides type-safe access to Banner database columns
type BannerFields struct{
	name string
}

func (f BannerFields) Name() string { return f.name }

func (f BannerFields) ID() BannerFields { return BannerFields{name: "id"} }
func (f BannerFields) NameVi() BannerFields { return BannerFields{name: "name_vi"} }
func (f BannerFields) NameEn() BannerFields { return BannerFields{name: "name_en"} }
func (f BannerFields) NameZh() BannerFields { return BannerFields{name: "name_zh"} }
func (f BannerFields) DescriptionVi() BannerFields { return BannerFields{name: "description_vi"} }
func (f BannerFields) DescriptionEn() BannerFields { return BannerFields{name: "description_en"} }
func (f BannerFields) DescriptionZh() BannerFields { return BannerFields{name: "description_zh"} }
func (f BannerFields) Position() BannerFields { return BannerFields{name: "position"} }
func (f BannerFields) Status() BannerFields { return BannerFields{name: "status"} }
func (f BannerFields) ResourceID() BannerFields { return BannerFields{name: "resource_id"} }
func (f BannerFields) Link() BannerFields { return BannerFields{name: "link"} }
func (f BannerFields) ButtonNameVi() BannerFields { return BannerFields{name: "button_name_vi"} }
func (f BannerFields) ButtonNameEn() BannerFields { return BannerFields{name: "button_name_en"} }
func (f BannerFields) ButtonNameZh() BannerFields { return BannerFields{name: "button_name_zh"} }
func (f BannerFields) HasContent() BannerFields { return BannerFields{name: "has_content"} }

